### Creates new user with shown parameters:
POST http://localhost:9090/user/createUser/
Content-Type: application/json

{
  "email": "igor@email.com",
  "username": "gottomy",
  "password" : "test1password",
  "privilege": "admin"
}

### Finds user with specified id:
GET http://localhost:9090/user/getUserById/1
### Updates User by Id

PUT http://localhost:9090/user/updateUser/
Content-Type: application/json

{
  "id": 1,
  "email": "changed@test.com",
  "username": "changeduser",
  "password": "changedpassword",
  "privilege": "admin"
}


### Create new Request:
POST http://localhost:9090/request/createRequest/
Content-Type: application/json

{
  "userId": 1,
  "url": "/todos/7",
  "host": "jsonplaceholder.typicode.com",
  "type": "GET"
}

###Gets request By Id:
GET  http://localhost:9090/request/getRequestById/3

### Updates Existing Request:
PUT http://localhost:9090/request/updateRequest/
Content-Type: application/json

{
  "id": 1,
  "userId": 1,
  "url": "http://test.com"
}

###
DELETE http://localhost:9090/request/deleteRequest/1


### Creates new Parameter:
POST http://localhost:9090/param/createParam/
Content-Type: application/json

{
  "requestId": 2,
  "name": "postId",
  "value": "1"
}

### Gets Parameter by id:
GET http://localhost:9090/param/getParamById/1


### Updates Parameter:
PUT http://localhost:9090/param/updateParam/
Content-Type: application/json

{
  "id": 1,
  "requestId": 2,
  "name": "username",
  "value": "igor"
}

### Creates new Response:
POST http://localhost:9090/response/createResponse
Content-Type: application/json

{
  "requestId":1,
  "response": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam volutpat lorem vestibulum, lobortis sapien a, gravida diam. Duis tempor velit eu diam semper volutpat. Nulla facilisi."
}

### Gets Response By Id:
GET http://localhost:9090/response/getResponseById/1

### Updates existing response:
PUT http://localhost:9090/response/updateResponse
Content-Type: application/json

{
  "id": 1,
  "requestId":2,
  "response": "Update Test"
}

### Creates new Scenario:
POST http://localhost:9090/scenario/createScenario/
Content-Type: application/json

{
  "userId": 1,
  "requestIds": "1/2/3",
  "name": "Test Scenario",
  "description": "Tests on google service"
}

### Get Scenario by id:
GET http://localhost:9090/scenario/getScenarioById/1


###
POST http://localhost:9090/request/sendRequest/1

###
POST http://localhost:9090/scenario/sendScenario/1

###
POST http://localhost:3000/requests/123
"Content-Type": "application/json"

{
  "userId": "1234",
  "Headers": {"Content-Type": "application/json"},
  "Params": {},
  "Body": {},
  "Host": "jsonplaceholder.typicode.com",
  "Method": "GET",
  "Url": "/todos/7"
}

###
GET http://localhost:3000/user/requests/1

###
GET http://localhost:3000/requests/3